# Quickstart: Black Duck Security Scan Action with polaris:
#     https://documentation.blackduck.com/bundle/bridge/page/documentation/t_github-polaris-quickstart.html
name: Polaris Security Scan
on:
  push:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  pull_request:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  workflow_dispatch: {}
jobs:
  polaris:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source & Setup JDK
        uses: actions/checkout@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven Wrapper
        run: ./mvnw -B package
      - name: Polaris Security Scan
        id: polaris-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          ### SCANNING: Required fields
          polaris_server_url: ${{ vars.POLARIS_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          ### ASSESSMENT TYPES
          polaris_assessment_types: SAST,SCA  # Comma-separated list: SAST,SCA,DAST
          ### Mark build status if policy violating issues are found
          mark_build_status: success  # Set to success, failure, or skip
          ### SCAN CONFIGURATION: Uncomment below to enable
          # polaris_waitForScan: true # Wait for scan completion before proceeding

          ### Uncomment below configuration if Bridge diagnostic files needs to be uploaded
          # include_diagnostics: false

          ### GITHUB TOKEN: Uncomment below to enable
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments or sarif reports enabled

          ### SCANNING: Optional fields
          # polaris_prComment_enabled: false

          ### SARIF report parameters
          # polaris_reports_sarif_create: false # Create SARIF report and upload it as artifact
          # polaris_upload_sarif_report: false # Upload SARIF report in GitHub Advanced Security tab
